# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161030_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='feedback_a',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='feedback_o',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='feedback_s',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
    ]
