# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161031_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='courses',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ass_text',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
