# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20161031_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_ao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.IntegerField(default=0)),
                ('option_2', models.IntegerField(default=0)),
                ('option_3', models.IntegerField(default=0)),
                ('option_4', models.IntegerField(default=0)),
                ('option_5', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback_o',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='feedback_o',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='feedback_o',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='feedback_o',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='feedback_o',
            name='option_5',
        ),
        migrations.RemoveField(
            model_name='feedback_o',
            name='qn_deadline',
        ),
        migrations.RemoveField(
            model_name='feedback_s',
            name='qn_deadline',
        ),
        migrations.AddField(
            model_name='feedback_f',
            name='form_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback_ao',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Feedback_o'),
        ),
    ]
