# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20161102_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('Full', 'Full'), ('Half', 'Half'), ('Summer', 'Summer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=20),
        ),
    ]
