# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20161104_0120'),
        ('main', '0023_remove_feedback_a_feed'),
    ]

    operations = [
    ]
