# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_name', models.CharField(max_length=200)),
                ('ass_deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='CS101', max_length=30)),
                ('course_name', models.CharField(default='Computer Programming', max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('num_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('student_roll', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_o',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('qn_deadline', models.DateTimeField()),
                ('option_1', models.IntegerField(default=0)),
                ('option_2', models.IntegerField(default=0)),
                ('option_3', models.IntegerField(default=0)),
                ('option_4', models.IntegerField(default=0)),
                ('option_5', models.IntegerField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('qn_deadline', models.DateTimeField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(default=0)),
                ('email_id', models.EmailField(max_length=254)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
            ],
        ),
        migrations.AddField(
            model_name='feedback_a',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Feedback_s'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
    ]
