# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_instruct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instruct',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
