# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161030_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ass_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ass_name',
            field=models.CharField(max_length=200),
        ),
    ]
