# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20161031_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_a',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Feedback_f'),
        ),
        migrations.AddField(
            model_name='feedback_ao',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Feedback_f'),
        ),
    ]
