# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_feedback_a_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_a',
            name='feed',
        ),
    ]
