# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20161103_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
